### ISSUE TITLE
Implement stylus PostCSS plugin

### ISSUE THREAD

**Issue by JoelRoxell** [JoelRoxell/TGIF-kit#8]
`https://github.com/seaneking/poststylus`

**Comment by JoelRoxell** [comment]
@LinusLjung -- v0.2.3 might be unstable, should we still use it ? I've implemented it and testet basic functionality. But have to test and include more PostCSS processes 🤑.

**Comment by LinusLjung** [comment]
I think it should be fine. We should definitely give it a shot!
